[source.crates-io]
replace-with = 'ustc'

[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

[target.x86_64-pc-windows-gnu]
linker = "/usr/bin/x86_64-w64-mingw32-gcc"
ar = "/usr/bin/x86_64-w64-mingw32-gcc-ar"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native"]

# [build]
# rustc-wrapper = "sccache"
